### ISSUE TITLE
Converting this to ESM

### ISSUE THREAD

**Issue by ayjayt** [cytoscape/cytoscape.js-dagre#120]
Hello! I'm about to start converting this to ESM (hopefully itll be as easy as the dependencies).

I have done the dependencies:

[graphlib](https://github.com/dagrejs/graphlib/pull/189)

[dagre](https://github.com/dagrejs/dagre/pull/434)

However, if the author doesn't pull and release them, then the official `npm` repos wont support ESM here either!

I want it and need it tho so I'll be using  a fork if I have to.

Pinging @maxkfranz for fun!

**Comment by ayjayt** [comment]
Do we know if there is a reason we depend on `dagre` and not the most recently maintained (still unmaintained) `@dagrejs/dagre`

possible incoming pain for me

**Comment by ayjayt** [comment]
Not packing `dagre` in w/ `cytoscape-dagre.js` seems a bit offbeat to me if using webpack.

**Comment by maxkfranz** [comment]
Should coordinate with https://github.com/cytoscape/cytoscape.js-automove/pull/34

**Comment by aloisklink** [comment]
FYI, there's an ESM fork of `dagre` at https://www.npmjs.com/package/dagre-d3-es.

It's not a one-to-one comparison though, since that fork combines:

- [dagre-d3](https://www.npmjs.com/package/dagre-d3)
- [dagre](https://www.npmjs.com/package/dagre)
- [graphlib](https://www.npmjs.com/package/graphlib)

Although, beware of the download count, I know it has over ~500k weekly downloads, but almost all of them are just from one project, so it it's not as well tested as the official `dagre` library.

**Comment by ayjayt** [comment]
@aloisklink I think they just merged my changes to the main library! So the main library should be native esm now. I'll be reviewing all this this weekend to see where we're at!

edit: it looks like they reverted them, am investigating

**Comment by ayjayt** [comment]
Yeah so, honestly, it seems kinda weird over there.

I think my conversions might be a hard pill to swallow, rollup provides a better experience.

But still, they reverted a dependency and not a defendant but I don't see how that builds, so. This project is on my backburner, but maybe I'll get back to it before anyone else does.
