### ISSUE TITLE
Rank confusion when using parent/compound nodes

### ISSUE THREAD

**Issue by tylerecouture** [cytoscape/cytoscape.js-dagre#14]
I'm running into odd behavior when the target of an edge is a parent/compound node
http://jsbin.com/ruguca/1/edit?html,output

I took the example and made n16 the parent of n5, and then made the edge go to the parent/compound node.

The result is that the compound node ends us in the same rank as the source, which seems like odd behaviour?

**Comment by maxkfranz** [comment]
If you decide to use compound graphs, you limit the layouts you can use.  Compound layouts need different logic than regular layouts.  Unless a layout explicitly mentions compound support, then it won't make special allowances for compound parents.

Use a different layout, don't use compound nodes (especially if they are being used without proper semantic need), or run the layout only on child nodes.

**Comment by maxkfranz** [comment]
Secondly, as mentioned in the readme, Dagre is a layout from an external lib.  Dagre's docs mention no support for compounds, so there's no way this layout can add support.

**Comment by tylerecouture** [comment]
Thank you, makes sense.  I appreciate you taking the time to reply and I am very thankful that you have provided this bridge to the dagre library.

I did figure out how to fake it, by creating direct node to node edges and hiding them. For future reference in case anyone else wants to use compound nodes with dagre, here's an example
http://jsbin.com/cipoqes/edit?html,output

**Comment by maxkfranz** [comment]
If that works for you, that's great.  Unfortunately, a lot of other libs don't have support for compound nodes --- and workarounds like yours work only if you can accommodate the dummy nodes.

Also consider [Cola](https://github.com/cytoscape/cytoscape.js-cola) with a specified `flow` -- which creates tree shapes.  It has support for compound nodes, and it will work with cases where a parent spans more than one depth.  It's not quite as fast as Dagre, because it's a physics layout that can be used on all graph types.
