### ISSUE TITLE
Layout bugged due to compound node order

### ISSUE THREAD

**Issue by riverchen99** [cytoscape/cytoscape.js-dagre#61]
The layout produced by dagre on graphs with compound nodes breaks when the parent node follows children nodes in the list of elements.

Please take a look at some additional details here: https://github.com/plotly/dash-cytoscape/issues/112

@xhlulu produced a [gist](https://github.com/plotly/dash-cytoscape/issues/112#issuecomment-722034848) reproducing the issue with pure javascript. 

Thanks!

**Comment by maxkfranz** [comment]
This looks like an issue within Dagre itself.  So the best way to resolve this would be to file an issue with Dagre: https://github.com/dagrejs/dagre/issues

If you can identify the root issue in Dagre, they may be open to a pull request.  Alternatively, if you can identify a workaround within this wrapper extension, I could help to review that PR so that at least Cytoscape users aren't affected by this issue.  It would be preferable to address the issue within [Dagre](https://github.com/dagrejs/dagre) so that even non-Cytoscape users benefit from the fix, though a workaround for Cytoscape users may be a bit faster.

**Comment by gabrywu** [comment]
So, what's the conclusion?

**Comment by marc-vdm** [comment]
It seems [dagre](https://github.com/dagrejs/dagre) is deprecated, will this issue be taken up here? Unfortunately, I don't have the JS expertise to help out but I'd benefit from having this in [Dash Cytoscape](https://github.com/plotly/dash-cytoscape)!
